export const FETCH_TOPSTORIES = "FETCH_TOPSTORIES";
export const FETCH_NEWSTORIES = "FETCH_NEWSTORIES";
export const FETCH_BESTSTORIES = "FETCH_BESTSTORIES";
export const FETCH_JOBSTORIES = "FETCH_JOBSTORIES";
export const FETCH_ASKSTORIES = "FETCH_ASKSTORIES";
export const FETCH_SHOWSTORIES = "FETCH_SHOWSTORIES";

export const FETCH_TOPNEWS = "FETCH_TOPNEWS";
export const FETCH_NEWNEWS = "FETCH_NEWNEWS";
export const FETCH_BESTNEWS = "FETCH_BESTNEWS";
export const FETCH_JOBNEWS = "FETCH_JOBNEWS";
export const FETCH_ASKNEWS = "FETCH_ASKNEWS";
export const FETCH_SHOWNEWS = "FETCH_SHOWNEWS";
